# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Schedule job to run every 2 weeks

on:
  schedule: # Every Monday at 6:00 in JST
    - cron: "0 21 * * 0"

  workflow_dispatch: # Manually trigger the workflow for testing
    inputs:
      current_date:
        description: 'The current date to check if it is biweekly (YYYY-MM-DD)'
        required: true

jobs:
  check-biweekly: # Job to determine if it runs every 2 weeks
    runs-on: ubuntu-latest
    outputs:
      is_biweekly: ${{ steps.check_biweekly.outputs.is_biweekly }}

    steps:
      - name: Determine If Biweekly
        id: check_biweekly
        run: |
          CURRENT_DATE=${{ github.event.inputs.current_date }}
          WEEK_NUM_STRING=$(date --date=$CURRENT_DATE +%U) # Get the week number of the current year (eg. 01, 02, ..., 52, 53) 
          WEEK_NUM=$((10#$WEEK_NUM_STRING)) # Convert the week number to decimal
          if [ $((WEEK_NUM % 2)) -eq 0 ]; then # Check if the week number is even
            echo "is_biweekly=true" >> $GITHUB_OUTPUT # Set the output to true if the week number is even
          else
            echo "is_biweekly=false" >> $GITHUB_OUTPUT # Set the output to false if the week number is odd
          fi

  biweekly-job: # Job that runs every 2 weeks
    needs: check-biweekly
    if: needs.check-biweekly.outputs.is_biweekly == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Run Biweekly Job
        run: |
          echo "This job runs only on biweekly basis according to the condition."
